### ISSUE TITLE
Question: why don't you use the request.Context()?

### ISSUE THREAD

**Issue by oliverpool** [ardanlabs/service#114]
In the HTTP Handler, I see that `ctx` is passed explicitly (along the `*http.Request`).

Do you have any reason not to use [`Request.Context()`](https://golang.org/pkg/net/http/#Request.Context)?
And [`Request.WithContext(ctx)`](https://golang.org/pkg/net/http/#Request.WithContext) when the context must be augmented.

---

Thanks for putting together this repo. It is a goldmine to learn more about structuring production-ready applications!

**Comment by ardan-bkennedy** [comment]
Yes, that pattern of keeping the context in the request might be ok when you are stuck using a router and can't change the handler. Even with that, once the request enters into the business layer, you will not pass the request to pass the context.

So I believe it is best to start passing the context as a parameter ASAP. Since this project creates its own handler, we can do that immediately. We do use the request context as the parent.

By passing the context as a parameter, it so doesn't hide the context and makes everything more precise.

**Comment by oliverpool** [comment]
Thank you for you quick reply.

If I understand correctly this is a tradeoff:
- a bit of duplication for every function (or handler) which gets a context and a request
- be more explicit for functions which don't get the Request as parameter

I think I would (personally) rather have only one context available in each function call, to be sure not to take the wrong one (a function which has a Context and a Request.Context could make use of the "wrong" context).

**Comment by ardan-bkennedy** [comment]
Read this post. What I am doing follows these guidelines

https://www.ardanlabs.com/blog/2019/09/context-package-semantics-in-go.html

**Comment by oliverpool** [comment]
> Even with that, once the request enters into the business layer, you will not pass the request to pass the context.

As soon as I reach the business layer, I can extract context from the Request and pass it to the business layer.

**Comment by ardan-bkennedy** [comment]
Since I control the web framework I decided to extract the context out of the request immediately and pass it down the call stack as the first parameter sooner. I believe it lends itself to more consistency in the code.

I also believe the Go team would have done the same with the http package if they didn’t have the backwards compatibility promise to adhere to. They would have changed the handler function to take a context. There solution to hide it in the request solved a problem.
