### ISSUE TITLE
sales-admin data model validation

### ISSUE THREAD

**Issue by jpreese** [ardanlabs/service#148]
Model validation currently happens within the `web` package through the `.Decode` function. This means that data that is added through the `admin` CLI won't go through the same validation checks. For example, attempting to add an email of "a" would fail through the HTTP handler, but would work if typed into the command line.

Since both of these scenarios are accepting user input which we do not have much control over, it feels like there should be some validation checks in the CLI as well. Thoughts?

**Comment by ardan-bkennedy** [comment]
Brilliant thought and you are right. I missed this for sure. I wanted this to be an app layer concern but at the same time tried to hide it in a foundational layer function. You can see how this get's lost when the CLI client doesn't use the same aspects of the foundation layer.

Here is the question?

Is this an application layer concern or really a business layer concern?

If this is a business layer concern, then we allow "bad data" to be passed in and it's checked there. We don't want to check it twice (both layers). It puts more complexity in the business layer and what if we miss this check? Then again, we're assuming the application layer has done this already and can be missed now.

Let's look at removing this from decode and having the proper business layer function handle this.

What are your thoughts?

**Comment by jpreese** [comment]
Given how the project is currently laid out, I think the only way to enforce that the model is valid is to have the data models in the business layer enforce it. We already do a little bit of it with some of the other inputs, e.g. https://github.com/ardanlabs/service/blob/fbd938d3a19f314e2a5391ecb1e32b03dafffd62/business/data/user/user.go#L142. 

It also feels like it would snap right into place because we're already taking the models that have these validation rules as input. e.g. to update a user, we pass in the `UpdateUser` model which has the validation tags on it already: https://github.com/ardanlabs/service/blob/fbd938d3a19f314e2a5391ecb1e32b03dafffd62/business/data/user/user.go#L87

The layers above, such as application, would still be free to reject the model for any domain-specific reasons, but at the end of the day we wouldn't want the validation rules we've applied to the model getting applied to the database such as wonky emails, or negative costs.

**Comment by ardan-bkennedy** [comment]
I’ll try It out in the morning and see how it feels. If it feels right, I’ll merge it. If not, I’ll add it to a branch and we can talk more.

Thanks for bringing this engineering discussion up.

**Comment by ardan-bkennedy** [comment]
@jpreese please check out this branch. I'm happy with it, but the changes need to be verified. I did my best to make sure the new validate package did not get imported by the web package. The error middleware is where there is a fusion of these two packages to create a trusted error for data invalidation errors.

I think it satisfies all the philosophy and design requirements.

https://github.com/ardanlabs/service/tree/john

**Comment by jpreese** [comment]
Looks great, Bill! Couple of thoughts:

I feel theres a slight inconsistency in how we handle invalid data. For example, when updating a `User` if the `userID` is invalid, we return an `ErrInvalidID`. When the model validation fails, we return a `validate.FieldErrors[]`. The validator package does have `uuid` validation, so the argument could be made that an invalid ID should also be a validation error. Otherwise I'm not sure when I would introduce a new error vs. use validation.

Building off of that, at the moment the HTTP layer handles validation errors through the middleware. So the middleware has to import the `validate` package, which I think can be justified. However, if a consumer of our User service wanted to further inspect the errors that the service returned, they'd have to import the validate package. i.e. We have a User service in package `user` that returns an error in package `validate`. This doesn't really matter much if the intent is to only ever print out the error, but something to consider.

In my opinion this leaves us with a few options:

1. Consider an invalid `uuid` a validation error to keep things a bit more consistent and leave the middleware / validate package errors as they are. I think this is the minimal step.

2. Beyond that we _could_ add another error type to each of the data models since we already have `ErrNotFound`, `ErrForbidden`, etc that is a Validation error which satisfies an interface like `.Fields()` which then our HTTP middleware could check for the existence of that. This would make it such that consumers of our services would get errors from the same package and removes the dependency on the types in the `validate` package. But without seeing it written down, I fear it may be stepping too far into over-engineering.

**Comment by ardan-bkennedy** [comment]
The BIG question is, is it wrong to have the CLI tool import package validate solely for the type information when it wants to inspect the errors? Regardless if this would ever be necessary.

I don't like the idea of importing a package for it's type system.

Maybe we can build a method based API around Fields for this type of functionality. That would solve this problem. Since I don't know if this functionality is really required, I would not want to engineer more.

 I am assuming printing is all that would be necessary.

**Comment by ardan-bkennedy** [comment]
I've merged that code and I think we can discuss this next change.

**Comment by jpreese** [comment]
> I've merged that code and I think we can discuss this next change.

Makes sense to me, easier to iterate 🎉

**Comment by ardan-bkennedy** [comment]
Technically there is not an inconsistency with ErrInvalidID and validate.FieldErrors.  Both represent an error value. ErrInvalidID happens to be a &errorString and the other a slice of FieldErrors. They both singal different events that occurred. You can't use an error variable for the field validation errors because this required much more context.

I don't believe a CLI user will have any need to inspect the concrete FieldErrors for processing. I think they will just be logged, so what we have now solves the initial problem you presented.

**Comment by ardan-bkennedy** [comment]
@jpreese I pushed some changes that I think resolve the rest of your concerns. This is something that I debated for a long time. 

I have moved the error types (except for shutdown) into the business layer in a new package called validate. So now validation and error types are a business concern. This allowed me to encapsulate the creating and validation of ID's in the business packages.

I am keeping the response unmarshal/marshaling in web (foundation) for now to be able to talk to that in class. Obviously, that could be moved out as well as a business concern.

I think putting this in a package called validate worked well. I could not call this errors since it would clash with the existing errors package we are using. Anything related to validation and errors fit in their nicely.

Please review and provide any thoughts.

**Comment by jpreese** [comment]
> The BIG question is, is it wrong to have the CLI tool import package validate solely for the type information when it wants to inspect the errors? Regardless if this would ever be necessary.
> 
> I don't like the idea of importing a package for it's type system.

This was my line of thinking as well. It didn't feel right to have a consumer interacting with the `user` package to have to import `validate` _just_ for the types. I've seen the opposite of this scenario in some packages I've used where the _input_ to a public method was actually a type from another package.

> Technically there is not an inconsistency with ErrInvalidID and validate.FieldErrors. Both represent an error value. ErrInvalidID happens to be a &errorString and the other a slice of FieldErrors. They both singal different events that occurred. You can't use an error variable for the field validation errors because this required much more context.

I agree in the sense that they both return errors, the inconsistency for me was why was UUID special compared to the other fields. 

- As a consumer of the package, if I put in an invalid UUID, I would expect a validation error for that field -- just like I would receive if I put in an invalid email address.
- As a maintainer of the package, I would not be sure when should I create a new error and check a field manually vs. running it through validation.

I do like the point about ID being foundational vs. business. The argument could be made that since there is not a `uuid` check on the model for validation, it's not a global concern -- but in this domain, we expect ID to be UUID.

> I don't believe a CLI user will have any need to inspect the concrete FieldErrors for processing. I think they will just be logged, so what we have now solves the initial problem you presented.

I felt the same way in that I _doubt_ a CLI user would ever need to do this, but since the error type is part of the public API for the user service.. they _could_. That situation felt weird if we ever got into it.

> Answer this question, should validate be a business package or stay as a foundation package?

As we have it right now, where the validation tags exist on models that are inside of the business package, I think it belongs in the business package. Otherwise we rely on callers of our service to first run validation, and if they don't we put ourselves into an inconsistent state.

Other domains are free to reject the model for whatever other reasons that domain dictates, but at the end of the day we have clearly defined rules that this data must _always_ adhere to, no matter its origin.

**Comment by ardan-bkennedy** [comment]
@jpreese good catch and fixed.

**Comment by jpreese** [comment]
Gave this another look over, and this does make more sense to me. The only other discussion point I can think of relating to validation would be the use of `init` in the `validation` package. 

I can make a lot of assumptions as to why it its used (ease of use, probably no need to fake validation results so injection isn't necessary), but as a reader of the code I don't concretely know the justification. 

If it does make sense in the design and/or plays a role in your class, like the Marshal/Unmarshal example, it may be worth a quick blurb as to why we chose to use `init` over newing up a validator and putting it in the data structs like db and log. This may help readers who stumble upon the repository to further learn when it's appropriate to use init.

**Comment by ardan-bkennedy** [comment]
The init is absolutely fine since it following the guidline for package level variables.

1. You don't need config to initialize it.
2. it doesn't matter what order the initialization occurs in as long as it happens before main.
3. Only the source code in this file touches the variables.

We do this in the metrics.go file as well and another place. I don't know if it makes sense to document this since it's a teaching moment that is talked about in class. I would then be required to sprinkle the entire code base with these types of notes.

Thoughts?

If you think we are done, let's close this issue.

**Comment by jpreese** [comment]
If it's a discussion point in class, I think it makes perfect sense. I'd say we're good to close.
