### ISSUE TITLE
add grpc

### ISSUE THREAD

**Issue by liyongjing** [ardanlabs/service#165]
Do you plan to add grpc into service?

**Comment by ardan-bkennedy** [comment]
Not at this time since it isn't needed. I would need to invent a new service (side car) that did something interesting for the problem this project is trying to solve. I haven’t thought of anything yet.

I believe in keeping things simple until I can’t. I don’t want complexity for the sake of it or to learn some new tech. There needs to be a need.

If you can think of a new sidecar that makes sense, I would love to hear it. Maybe we can work on it together.
