### ISSUE TITLE
Handle panic in a goroutine

### ISSUE THREAD

**Issue by nhaancs** [ardanlabs/service#178]
Hi there,

Thank you for publishing a valuable source code. 
I have faced a case that if my handler code causes panic in a goroutine, that panic won't be caught by panic middleware, and the app will be crashed. How we can handle this case. Thank you!

Example code:

```go
func (ug userGroup) token(ctx context.Context, w http.ResponseWriter, r *http.Request) error {
	go func ()  {
		panic("test panic in a goroutine")
	}()
...
```

**Comment by ardan-bkennedy** [comment]
You are causing a panic in a separate Goroutine (G), the middleware is not involved.

You don't really want to process anything for a request in a separate G. If you are going to do this (which I don't recommend), you can't orphan that G because if you shut down the service, it will be terminated mid work. You can't use the context from the original G executing the request.

Several things. There is a worker package under foundation for these types of senarios. The Worker package let's you register job functions that can be executed by name. Then in main.run() you can register everything and wait for all those G's to complete before shutting down. You need this or something like it.

Second, you will need to add your own defer / recover code in the worker function or any function being executed as a separate G. You can look at the panics middleware for that code.
