### ISSUE TITLE
Question: relating entities

### ISSUE THREAD

**Issue by eternalblue** [ardanlabs/service#262]
If i have an Users and Posts I have in core two folders by each entity; how about if Post is related to User
```golang
type User struct {
    posts []Posts
}
```
- where should I put my queries in the store of User and make the join in the userdb.go?
- I'll be relating a model from core/post in core/user is this ok?

**Comment by ardan-bkennedy** [comment]
You can't have joins at the storage layer, you want to keep the User and Posts domains separated. Believe that each domain stores its data in a separate unknown database running in some unknow location. Believe that each business core API is something you don't own, and need to use to get the data for that specific domain. At the app layer you can join all the data you want.

If you use joins between domains at the storage or business layer, you are merging those domains, essentially creating a single domain of many different pieces of data. This is going to allow for some bad practices that will make it harder and harder for you to expand, grow, and scale the product and solution. Work hard to make things easy to understand, not easy to do.

Looking at your example I think you have it wrong. A Post should probably have a UserID, not the other way around. No User model can have a concept of a Post, but a Post can have the concept of a User.

I imagine something like this.

Storage Layer For User
```
CREATE TABLE Users (
  id    UUID  NOT NULL
  name  TEXT  NOT NULL
)
```

Storage Layer For Post
```
CREATE TABLE Posts (
  id       UUID  NOT NUL
  user_id  UUID  NOT NULL
)
```

Business Core Layer For User
```
core/user/model.go

type User struct {
  ID    uuid.UUID
  Name  string
}
```

Business Core Layer For Post
```
core/post/model.go

type Post struct {
  ID     uuid.UUID
  UserID uuid.UUID
}
```

Now at the App layer you can create models with mixed fields.

```
app/services/api/handlers/v1/postgrp/model.go

type App struct {
    ID        uuid.UUID
    UserID    uuid.UUID
    UserName  string
}
```

In the Handler function you would make the business call to query the posts and then call into the User domain core API to get the name for each unique ID in the result.

The Post Domain can use the User Domain API because of the relationship with the UserID being in the model. The User Domain can't use the Post Domain API. Plus Go won't allow cross imports, so the data is telling you what is the right direction for the imports.

In the end, you can only order and filter data at tha domain level. A domain can only access another domain if there is a relationship in the data. This access is NEVER at the storage layer.  At the App layer you have a lot of flexibility.

**Comment by ardan-bkennedy** [comment]
You need to pretend the data is not all in the same database where a join is even possible. What if the data for User and Post were in different databases on different servers? How would you handle that situation? That is what I'm describing here.

In the end, if you store this data in the same place, then all this data represents the domain, and you can do joins. But you are losing the ability to scale in different ways. So fight that and work towards treating each piece of the data model as separate data stores.
