### ISSUE TITLE
API Layer Made Thinner

### ISSUE THREAD

**Issue by ameghdadian** [ardanlabs/service#439]
Hi!

I've been tracking this repo for a while. As far as I can recall, we started with three layers being: `App`, `Business` and `Storage`(as well a separate folder for foundational concerns).

Then we moved to having another layer, called `API` to separate protocol concerns which I really appreciated the move since `service` project is:

> Starter-kit for writing services in Go using Kubernetes

Afterwards, at this commit [#e70ef86](https://github.com/ardanlabs/service/commit/e70ef86fed96114e86a8ccd7337170f8ca9b0907), we pretty much reverted all the stuff we had that made that separation of concerns possible.

I'd really appreciate if you could help me understand whether I am missing something or any justifications as to why we removed that part? 

Are we going to bring that back in some other form?

**Comment by ardan-bkennedy** [comment]
I've worked on several project since I introduced the API layer owning the handler functions and it's been overkill for those projects. If you are only working with one transport (which is most of the time), it's best to keep the handlers in the App layer. I have a branch in the repo called `api-layer` that has that code for when I will need it.

Keep it simple until you can't.
